export const GET_USER_LOADING="GET_USER_LOADING";
export const GET_USER_LOADED="GET_USER_LOADED";
export const GET_USER_ERROR="GET_USER_ERROR";


export const GET_VOUCHER_LOADING="GET_VOUCHER_LOADING";
export const GET_VOUCHER_LOADED="GET_VOUCHER_LOADED";
export const GET_VOUCHER_ERROR="GET_VOUCHER_ERROR";

export const POST_VOUCHER_LOADING="POST_VOUCHER_LOADING";
export const POST_VOUCHER_LOADED="POST_VOUCHER_LOADED";
export const POST_VOUCHER_ERROR="POST_VOUCHER_ERROR";

export const EDIT_VOUCHER_LOADING="EDIT_VOUCHER_LOADING";
export const EDIT_VOUCHER_LOADED="EDIT_VOUCHER_LOADED";
export const EDIT_VOUCHER_ERROR="EDIT_VOUCHER_ERROR";


export const DELETE_VOUCHER_LOADING="DELETE_VOUCHER_LOADING";
export const DELETE_VOUCHER_LOADED="DELETE_VOUCHER_LOADED";
export const DELETE_VOUCHER_ERROR="DELETE_VOUCHER_ERROR";