export const GET_USER_LOADING="GET_USER_LOADING";
export const GET_USER_LOADED="GET_USER_LOADED";
export const GET_USER_ERROR="GET_USER_ERROR";

// export const CREATE_USER="CREATE_USER";
// export const UPDATE_USER="UPDATE_USER";
// export const DELETE_USER="DELTE_USER";
